/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {},
    colors: {
      Danger10: '#FBF4F4',
      Danger20: '#F8E9E9',
      Danger30: '#F0D2D2',
      Danger40: '#D37979',
      Danger50: '#D37979',
      Danger60: '#C44C4C',
      Danger70: '#B61F1F',
      Danger80: '#A00A0A',
      Neutral80: '#140A08',
      Neutral70: '#433B39',
      Neutral60: '#726C6B',
      Neutral50: '#D0CECE',
      Neutral40: '#E7E6E6',
      Neutral30: '#F3F3F3',
      Neutral20: '#FAFAFA',
      Neutral10: '#FFFFFF',
      Yellow80: '#72510D',
      Yellow70: '#D8940E',
      Yellow60: '#F2AF29',
      Yellow50: '#F5BF54',
      Yellow40: '#F7CF7F',
      Yellow30: '#FADFA9',
      Yellow20: '#FCEFD4',
      Yellow10: '#FEF7EA',
      Blue80: '#26435E',
      Blue70: '#3877B2',
      Blue60: '#4891D4',
      Blue50: '#6CA7DD',
      Blue40: '#91BDE5',
      Blue30: '#B6D3EE',
      Blue20: '#DAE9F6',
      Blue10: '#EDF4FB',

      Primary80: '#0E390E',
      Primary70: '#186218',
      Primary60: '#228B22',
      Primary50: '#4EA24E',
      Primary40: '#7AB97A',
      Primary30: '#BDDCBD',
      Primary20: '#E9F3E9',
      Primary10: '#F4F9F4',
      PrimaryHue: '#89C01C',
      PrimaryGradient: '-webkit-linear-gradient(90deg, #2A9428 0%, #89C22D 100%)',

      Secondary80: '#140A08',
      Secondary70: '#230803',
      Secondary60: '#543731',
      Secondary50: '#765F5A',
      Secondary40: '#988783',
      Secondary30: '#BAAFAD',
      Secondary20: '#DDD7D6',
      Secondary10: '#EEEBEA',

      SecondaryHuw: '#9F7143',
      SecondaryGradient: 'linear-gradient(180deg, #543731 0%, #9F7143 100%)'



    },
    container: {
      maxWidth: {
        xl: '1224px',
      }
    },

    fontSize: {
      'Medium+/Display/Large': ['64px', {
        fontFamily: 'Manrope',
        fontStyle: 'normal',
        fontWeight: '700',
        lineHeight: '72px',
        letterSpacing: '-4%',
      }],
      'Medium+/Display/Medium': ['48px', {
        fontFamily: 'Manrope',
        fontStyle: 'normal',
        fontWeight: '700',
        lineHeight: '64px',
        letterSpacing: '-4%',
      }],
      'Medium+/Title/xxLarge': ['64px', {
        fontFamily: 'Manrope',
        fontStyle: 'normal',
        fontWeight: '700',
        lineHeight: '76px',
        letterSpacing: '-2%',
      }],
      'Medium+/Title/xLarge': ['48px', {
        fontFamily: 'Manrope',
        fontStyle: 'normal',
        fontWeight: '700',
        lineHeight: '56px',
        letterSpacing: '-2%',
      }],
      'Medium+/Title/Large': ['40px', {
        fontFamily: 'Manrope',
        fontStyle: 'normal',
        fontWeight: '700',
        lineHeight: '48px',
        letterSpacing: '-2%',
      }],

      'Medium+/Title/Medium': ['32px', {
        fontFamily: 'Manrope',
        fontStyle: 'normal',
        fontWeight: '700',
        lineHeight: '40px',
        letterSpacing: '-1.5%',
      }],

      'Medium+/Title/Small': ['24px', {
        fontFamily: 'Manrope',
        fontStyle: 'normal',
        fontWeight: '700',
        lineHeight: '28px',
        letterSpacing: '-1.5%',
      }],
      'Medium+/Title/xSmall': ['18px', {
        fontFamily: 'Manrope',
        fontStyle: 'normal',
        fontWeight: '700',
        lineHeight: '24px',
        letterSpacing: '-1.5%',
      }],
      'Medium+/Title/xxsmall': ['14px', {
        fontFamily: 'Manrope',
        fontStyle: 'normal',
        fontWeight: '700',
        lineHeight: '20px',
        letterSpacing: '-5%',
      }],
      'Medium+/Paragraph/Large': ['18px', {
        fontFamily: 'Manrope',
        fontStyle: 'normal',
        fontWeight: '400',
        lineHeight: '28px',
        letterSpacing: '-1.5%',
      }],
      'Medium+/Paragraph/Large-Strong': ['18px', {
        fontFamily: 'Manrope',
        fontStyle: 'normal',
        fontWeight: '600',
        lineHeight: '28px',
        letterSpacing: '-1.5%',
      }],
      'Medium+/Paragraph/Medium': ['16px', {
        fontFamily: 'Manrope',
        fontStyle: 'normal',
        fontWeight: '400',
        lineHeight: '24px',
        letterSpacing: '-1.5%',
      }],
      'Medium+/Paragraph/Medium-Strong': ['16px', {
        fontFamily: 'Manrope',
        fontStyle: 'normal',
        fontWeight: '600',
        lineHeight: '24px',
        letterSpacing: '-1.5%',
      }],
      'Medium+/Paragraph/Small': ['14px', {
        fontFamily: 'Manrope',
        fontStyle: 'normal',
        fontWeight: '400',
        lineHeight: '20px',
        letterSpacing: '-1.5%',
      }],
      'Medium+/Paragraph/Small-Strong': ['14px', {
        fontFamily: 'Manrope',
        fontStyle: 'normal',
        fontWeight: '600',
        lineHeight: '20px',
        letterSpacing: '-1.5%',
      }],
      'Medium+/Paragraph/xSmall': ['12px', {
        fontFamily: 'Manrope',
        fontStyle: 'normal',
        fontWeight: '400',
        lineHeight: '16px',
        letterSpacing: '-1.5%',
      }],
      'Medium+/Paragraph/xSmall-Strong': ['12px', {
        fontFamily: 'Manrope',
        fontStyle: 'normal',
        fontWeight: '600',
        lineHeight: '16px',
        letterSpacing: '-1.5%',
      }],

      'Medium+/Label/Large': ['18px', {
        fontFamily: 'Manrope',
        fontStyle: 'normal',
        fontWeight: '400',
        lineHeight: '24px',
        letterSpacing: '-1%',
      }],
      'Medium+/Label/Large-Strong': ['18px', {
        fontFamily: 'Manrope',
        fontStyle: 'normal',
        fontWeight: '600',
        lineHeight: '24px',
        letterSpacing: '-1%',
      }],
      'Medium+/Label/Medium': ['16px', {
        fontFamily: 'Manrope',
        fontStyle: 'normal',
        fontWeight: '400',
        lineHeight: '20px',
        letterSpacing: '-1%',
      }],
      'Medium+/Label/Medium-Strong': ['16px', {
        fontFamily: 'Manrope',
        fontStyle: 'normal',
        fontWeight: '600',
        lineHeight: '20px',
        letterSpacing: '-1%',
      }],
      'Medium+/Label/Small': ['14px', {
        fontFamily: 'Manrope',
        fontStyle: 'normal',
        fontWeight: '400',
        lineHeight: '16px',
        letterSpacing: '-1%',
      }],
      'Medium+/Label/Small-Strong': ['14px', {
        fontFamily: 'Manrope',
        fontStyle: 'normal',
        fontWeight: '600',
        lineHeight: '16px',
        letterSpacing: '-1%',
      }],
      'Medium+/Label/xSmall ': ['12px', {
        fontFamily: 'Manrope',
        fontStyle: 'normal',
        fontWeight: '400',
        lineHeight: '16px',
        letterSpacing: '-1%',
      }],
      'Medium+/Label/xSmall-Strong': ['12px', {
        fontFamily: 'Manrope',
        fontStyle: 'normal',
        fontWeight: '600',
        lineHeight: '16px',
        letterSpacing: '-1%',
      }],
      
  }
},
  plugins: [],
}
